name: Backend CI

on:
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Set up JDK 11
      uses: actions/setup-java@v3
      with:
        java-version: '11'
        distribution: 'temurin'

    - name: Grant execute permission for gradlew
      run: chmod +x gradlew

    - name: Build with Gradle
      run: ./gradlew build

    - name: Publish Unit Test Results
      uses: EnricoMi/publish-unit-test-result-action@v2
      if: always()
      with:
        junit_files: ${{ github.workspace }}/build/test-results/**/*.xml
    
    
    services:
      kafka:
        image: confluentinc/cp-kafka:latest
        ports:
          - 9092:9092
        options: >-
          --env ADVERTISED_LISTENERS=PLAINTEXT://kafka:9092
          --env KAFKA_LISTENERS=PLAINTEXT://0.0.0.0:9092
          --env KAFKA_LISTENER_SECURITY_PROTOCOL_MAP=PLAINTEXT:PLAINTEXT
          --env KAFKA_INTER_BROKER_LISTENER_NAME=PLAINTEXT
          --env KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR=1
        env:
          KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://localhost:9092
